version: '3.8'

services:
  fastapi_app:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
#    image: atemndobs/fastapi:v1.9
    ports:
      - "2222:80"
      - "2224:8081"
      - "5555:1234"

    restart: on-failure
    volumes:
      - ./app:/code/app

networks:
  default:
    name: laravel_sail
    external: true