version: '3.8'

services:
  fastapi_app:
    container_name: fastapi
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: atemndobs/fastapi:v1.9
    ports:
      - "2222:80"

    restart: on-failure
    volumes:
      - ./app:/code/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80",--reload]

networks:
  default:
    name: laravel_sail
    external: true