services:
  fastapi_app:
    container_name: fastapi
    image: atemndobs/fastapi-amd64:v0.0.3
    ports:
      - "2222:80"
      - "2224:8081"
      - "5555:1234"
    volumes:
      - ./app:/code/app
    environment:
      GOOGLE_MAPS_API_KEY: ""  # Add your actual API key here
