services:
  fastapi_app:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:80"
      - "2224:8081"
      - "5555:1234"
    volumes:
      - ./app:/code/app
    environment:
      GOOGLE_MAPS_API_KEY: "AIzaSyB_mUQGA1yNwhRg1TuZ6nsAdtjVAzs0djo"  # Add your actual API key here
