name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure Git
        run: |
          git config user.name "Atemndobs"
          git config user.email "atemndobs@yahoo.com"

      - name: Build and push Docker image
        run: |
          docker build -t atemndobs/fastapi:${{ github.sha }} .
          docker push atemndobs/fastapi:${{ github.sha }}
