name: Build and Push Docker Image with Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: gettag
        run: |
          git fetch --tags
          echo "::set-output name=version::$(echo $(git describe --tags $(git rev-list --tags --max-count=1)) | sed 's/v//')"

      - name: Increment version
        id: incver
        run: |
          major_version=$(echo ${{ steps.gettag.outputs.version }} | cut -d. -f1)
          minor_version=$(echo ${{ steps.gettag.outputs.version }} | cut -d. -f2)
          echo "Major Version: $major_version"
          echo "Minor Version: $minor_version"
          incremented_minor_version=$((minor_version + 1))
          new_version="$major_version.$incremented_minor_version"
          echo "New Version: v$new_version"
          echo "::set-output name=newversion::v1.6"

      - name: Set new tag to current commit
        run: git tag ${{ steps.incver.outputs.newversion }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t atemndobs/fastapi:${{ steps.incver.outputs.newversion }} .
          docker push atemndobs/fastapi:${{ steps.incver.outputs.newversion }}


      - name: Configure Git
        run: |
          git config user.name "Atemndobs"
          git config user.email "atemndobs@yahoo.com"

#      - name: Push new tag to repository
#        run: |
#          git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Atemndobs/fastapi.git ${{ steps.incver.outputs.newversion }}
